name: Deploy Changes

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.accessKeyId }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.secretAccessKey }}
  AWS_REGION: ${{ secrets.region }}
  AWS_PLATFORM: "Node.js"

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Install EB
        run: |
          pip install awsebcli --upgrade --user
          echo 'export PATH="~/.local/bin"' >> ~/.bash_profile && source ~/.bash_profile
          eb --version
      - name: Configure EB
        run: |
          eb init TimothyCope.com --region ${AWS_REGION} --platform ${AWS_PLATFORM}
      - name: Deploy EB
        run: |
          eb deploy TimothyCopeCom-env-1 --label `date +%s`
