name: Deploy Changes

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

env:
  accessKeyId: ${{ secrets.accessKeyId }}
  secretAccessKey: ${{ secrets.secretAccessKey }}
  region: ${{ secrets.region }}

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      # Create config - Creates the ./timothy-cope/config.json file used to authenticate with AWS
      - name: Create config
        run: |
          foo="{ 'accessKeyId': ${accessKeyId}, 'secretAccessKey': ${secretAccessKey}, 'region': ${region} }"
          echo ${foo} > timothy-cope/config.json
      # Zips the contents of ./timothy-cope
      - name: Zip contents
        run: |
          zip -r timothy-cope.zip timothy-cope
      # Install EB CLI
      - name: Install EB
        run: |
          git clone https://github.com/aws/aws-elastic-beanstalk-cli-setup.git
          python ./aws-elastic-beanstalk-cli-setup/scripts/ebcli_installer.py
      # Use EB CLI
      - name: Use EB
        run: |
          eb --version
