name: Deploy Changes

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  accessKeyId: ${{ secrets.accessKeyId }}
  secretAccessKey: ${{ secrets.secretAccessKey }}
  region: ${{ secrets.region }}

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    # Foo - Creates a file
    - name: Foo
      run: |
        foo="{ 'accessKeyId': ${accessKeyId}, 'secretAccessKey': ${secretAccessKey}, 'region': ${region} }"
        echo ${foo}
        echo $accessKeyId
        touch config.json
