name: Deploy Changes

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.accessKeyId }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.secretAccessKey }}
  AWS_REGION: ${{ secrets.region }}

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      # Create config - Creates the ./timothy-cope/config.json file used to authenticate with AWS
      - name: Create config
        run: |
          foo="{ 'accessKeyId': ${AWS_ACCESS_KEY_ID}, 'secretAccessKey': ${AWS_SECRET_ACCESS_KEY}, 'region': ${AWS_REGION} }"
          echo ${foo} > timothy-cope/config.json
      # Zips the contents of ./timothy-cope
      - name: Zip contents
        run: |
          zip -r timothy-cope.zip timothy-cope
      # Install EB CLI
      - name: Install EB
        run: |
          pip install awsebcli --upgrade --user
          echo 'export PATH="~/.local/bin"' >> ~/.bash_profile && source ~/.bash_profile
          eb --version
      # Use EB CLI
      - name: Use EB
        run: |
          eb init TimothyCope.com --region ${AWS_REGION}
