name: Deploy Changes

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.accessKeyId }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.secretAccessKey }}
  AWS_REGION: ${{ secrets.region }}
  AWS_PLATFORM: "Node.js"

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Prepare zip
        run: |
          config="{ 'accessKeyId': ${AWS_ACCESS_KEY_ID}, 'secretAccessKey': ${AWS_SECRET_ACCESS_KEY}, 'region': ${AWS_REGION} }"
          echo ${config} > timothy-cope/config.json
      - name: Zip contents
        run: |
          cd timothy-cope && zip -r timothy-cope.zip ./*
      - name: Install EB
        run: |
          pip install awsebcli --upgrade --user
          echo 'export PATH="~/.local/bin"' >> ~/.bash_profile && source ~/.bash_profile
          eb --version
      - name: Configure EB
        run: |
          eb init TimothyCope.com --region ${AWS_REGION} --platform ${AWS_PLATFORM}
          echo '\ndeploy:\nartifact: timothy-cope.zip' >> .elasticbeanstalk/config.yml
          eb status
      - name: Deploy website
        run: |
          eb deploy TimothyCopeCom-env --label `date +%s` --staged
